### ISSUE TITLE
`devices` support suggestive text in UI

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#257]
Add the following text to the apps page, maybe as a commented text inside the text area, or aligned with the "Docker compose " question mark, on the right side of the box. Name it "Using devices, capabilities or privileged?":

>    Docker does not support `devices`, `capabilities` nor `privileged` for Docker services.
>    **However**, you can work around this limitation by adapting your compose file as shown below:

```yaml
    services:
        myIoTservice:
            image: your_repo/your_image
            devices:
                - "/dev/ttyUSB0:/dev/ttyUSB0"
```
>    **becomes**

```yaml
    services:
        myIoTserviceWrapper:
            image: docker
            volumes: 
                - /var/run/docker.sock:/var/run/docker.sock
            command: sh -c 'docker run --rm -d -v /var/run/docker.sock:/var/run/docker.sock -e PARENT=$$(basename "$$(head /proc/1/cgroup)") -e CHILD=myIoTservice sixsq/wrapper-cleaner:master && docker run --rm --device /dev/ttyUSB0:/dev/ttyUSB0 --name myIoTservice your_repo/your_image' 
```

Please also add a **bold** note about the limitation of this workaround, saying that "Please note that this workaround might require significant changes to your compose file if you're using Docker Stack/Service specific options"

**Comment by konstan** [comment]
After discussion with @cjdcordeiro, this solution is really applicable not only to devices. E.g., I will apply it now in GNSS for capabilities.  Hence, for clarity, I'm suggesting to change the name of `sixsq/device-map-cleaner` to something `sixsq/container-wrapper` or `...-helper`.

**Comment by konstan** [comment]
Here is the example for the change that had to be made to the compose file to enable `--cap-add=sys_nice` on a service that uses `configs`, `volumes` and `environment`.

In the example, the service name is `datasp`. `datasp` requires another service `mta` running along side, and they communicate via a named volume `mta-datasp` (`datasp` is writing `mta` is reading and writing). `datasp` requires two configuration files.

Before

```
version: "3.7"

# Environment vars provided by Nuvla.
x-nuvla_env: &nuvla_env
  NUVLA_DEPLOYMENT_ID: $NUVLA_DEPLOYMENT_ID
  NUVLA_ENDPOINT: $NUVLA_ENDPOINT
  NUVLA_API_KEY: $NUVLA_API_KEY
  NUVLA_API_SECRET: $NUVLA_API_SECRET

services:
  datasp:
    image: registry-gnss.nuv.la/data-sp:dbg
    volumes:
      - mta-datasp:/var/tmp/mta
    configs:
      - source: osrl.conf
        target: /etc/gifres/osrl.conf
      - source: datasp_config.xml
        target: /dist_dataSP/datasp_config.xml
    networks:
      - host
    environment:
      <<: *nuvla_env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 1s
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == gifres.station.datasp
  mta:
    image: registry-gnss.nuv.la/mta:2.2.0
    volumes:
      - mta-datasp:/var/tmp/mta
    configs:
      - source: osrl.conf
        target: /etc/mta.conf
    environment:
      <<: *nuvla_env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == gifres.station.datasp

networks:
   host:
     external: true
volumes:
    mta-datasp:
configs:
    osrl.conf:
      file: ./osrl.conf
    datasp_config.xml:
      file: ./datasp_config.xml
```

After

```
version: "3.7"

# Environment vars provided by Nuvla.
x-nuvla_env: &nuvla_env
  NUVLA_DEPLOYMENT_ID: $NUVLA_DEPLOYMENT_ID
  NUVLA_ENDPOINT: $NUVLA_ENDPOINT
  NUVLA_API_KEY: $NUVLA_API_KEY
  NUVLA_API_SECRET: $NUVLA_API_SECRET

services:
  datasp-wrapper:
    image: docker
    volumes:
      - mta-datasp:/var/tmp/mta
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command: >
      sh -c 'set -x; export CONFDIR=$$(mktemp -d -p /tmp); 
      cp /etc/gifres/osrl.conf $${CONFDIR}/osrl.conf; 
      cp /dist_dataSP/datasp_config.xml $${CONFDIR}/datasp_config.xml; 
      export PARENT=$$(basename "$$(head /proc/1/cgroup)"); 
      export CONT_NAME=datasp; 
      docker run -d -v /var/run/docker.sock:/var/run/docker.sock -e PARENT -e CHILD=$${CONT_NAME} registry-gnss.nuv.la/docker-cleaner:linux
      && docker run --rm -v mta-datasp:/var/tmp/mta -v $${CONFDIR}:$${CONFDIR}:ro --network host --name $${CONT_NAME} -e NUVLA_DEPLOYMENT_ID -e NUVLA_ENDPOINT -e NUVLA_API_KEY -e NUVLA_API_SECRET --entrypoint="" registry-gnss.nuv.la/data-sp:dbg bash -c "ls -la $${CONFDIR}; mkdir -p /etc/gifres/ /dist_dataSP/; cp $${CONFDIR}/osrl.conf /etc/gifres/osrl.conf; cp $${CONFDIR}/datasp_config.xml /dist_dataSP/datasp_config.xml; ./dataSP"'
    configs:
      - source: osrl.conf
        target: /etc/gifres/osrl.conf
      - source: datasp_config.xml
        target: /dist_dataSP/datasp_config.xml
    networks:
      - host
    environment:
      <<: *nuvla_env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 10s
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == gifres.station.datasp
  mta:
    image: registry-gnss.nuv.la/mta:2.2.0
    volumes:
      - mta-datasp:/var/tmp/mta
    configs:
      - source: osrl.conf
        target: /etc/mta.conf
    environment:
      <<: *nuvla_env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == gifres.station.datasp

networks:
   host:
     external: true
volumes:
    mta-datasp:
      external: true
configs:
    osrl.conf:
      file: ./osrl.conf
    datasp_config.xml:
      file: ./datasp_config.xml
```

To simplify `mta-datasp` volume propagation from `datasp-wrapper` service to `datasp` container, I created `mta-datasp` on the docker host in advance and I'm using it as `external: true`. If creation of the volume in advance is not possible, startup of `datasp` container from `datasp-wrapper` should like so

```
export VOL_NAME="$$(docker inspect $${PARENT} --type container --format "{{json .Name}}" | sed "s|[\"/]||g" | awk -F_ "{print $$1}" )_mta-datasp" 
&& docker run --rm -v $${VOL_NAME}:/var/tmp/mta -v $${CONFDIR}:$${CONFDIR}:ro 
--network host --name $${CONT_NAME} -e NUVLA_DEPLOYMENT_ID -e NUVLA_ENDPOINT 
-e NUVLA_API_KEY -e NUVLA_API_SECRET --entrypoint="" 
registry-gnss.nuv.la/data-sp:dbg bash -c 
"ls -la $${CONFDIR}; mkdir -p /etc/gifres/ /dist_dataSP/; cp $${CONFDIR}/osrl.conf /etc/gifres/osrl.conf; cp $${CONFDIR}/datasp_config.xml /dist_dataSP/datasp_config.xml; ./dataSP"
```

**Warning:** This solution leaves service `datasp` service configuration files on the docker host under `/tmp`.

**Comment by konstan** [comment]
@cjdcordeiro Is there a way to cleanup `${CONFDIR}` after the termination of the wrapper service? Can this be done via `cleaner` container?

**Comment by cjdcordeiro** [comment]
it could, but not in a generic way cause you would need to also share /tmp with the wrapper-cleaner

**Comment by cjdcordeiro** [comment]
not needed anymore since now we support native docker compose

**Comment by konstan** [comment]
@cjdcordeiro how does the fact docker compose is supported translates into deployment with devices on clusters? Because below doesn't work on cluster (devices and caps are ignored)

```
    deploy:
      placement:
        constraints:
          - node.labels.type == gifres.user
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
```

and one has still to resort to this

```
services:
  jupyter:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *nuvla_env
    command: >
      sh -c 'set -x;
      export PARENT=$$(basename "$$(head /proc/1/cgroup)");
      export CONT_NAME=jupyter_$$(date +%s);
      docker run -d -v /var/run/docker.sock:/var/run/docker.sock -e PARENT -e CHILD=$${CONT_NAME} registry-gnss.nuv.la/docker-cleaner:linux
      && docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged --cap-add=SYS_ADMIN --device /dev/fuse --rm -P --name $${CONT_NAME} --user root -e GRANT_SUDO=yes -e CONT_NAME -e NUVLA_DEPLOYMENT_ID -e NUVLA_ENDPOINT -e NUVLA_API_KEY -e NUVLA_API_SECRET registry-gnss.nuv.la/example-jupyter:0.2.4'
    deploy:
      placement:
        constraints:
          - node.labels.type == gifres.user
```

Unless, I'm missing something.

**Comment by cjdcordeiro** [comment]
no, docker compose will only deploy to the endpoint node. 

What we have now in Nuvla is representative of the Docker capabilities: compose for single node orchetsration + swarm COE for clusters. 

That compose file 
```
    deploy:
      placement:
        constraints:
          - node.labels.type == gifres.user
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
``` 
is neither docker-compose nor swarm compliant. We default it to Swarm, meaning that devices and cap are ignored, and a warning is shown to the user.

If you still think it is useful to have those instructions, then I don't think it would harm to have a section in the docs about "Using Compose options in Swarm"
